// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnC-hrvgfZJaPNmyI8PD_3GtNPb1RRr9M',
    appId: '1:317448814289:web:43b8297168946f7aeb0ff0',
    messagingSenderId: '317448814289',
    projectId: 'rental-app-2ba43',
    authDomain: 'rental-app-2ba43.firebaseapp.com',
    storageBucket: 'rental-app-2ba43.appspot.com',
    measurementId: 'G-ZK6ZBLPSKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVKL4n3uRfL5-zE7m5CH5jXTb8IlYjfQ',
    appId: '1:317448814289:android:428574c2807594a5eb0ff0',
    messagingSenderId: '317448814289',
    projectId: 'rental-app-2ba43',
    storageBucket: 'rental-app-2ba43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRxEbEEsMn0SEXemGmlZYjwpIem_UG-E',
    appId: '1:317448814289:ios:014206f5ae718293eb0ff0',
    messagingSenderId: '317448814289',
    projectId: 'rental-app-2ba43',
    storageBucket: 'rental-app-2ba43.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbRxEbEEsMn0SEXemGmlZYjwpIem_UG-E',
    appId: '1:317448814289:ios:014206f5ae718293eb0ff0',
    messagingSenderId: '317448814289',
    projectId: 'rental-app-2ba43',
    storageBucket: 'rental-app-2ba43.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnC-hrvgfZJaPNmyI8PD_3GtNPb1RRr9M',
    appId: '1:317448814289:web:ab1c49fe85456274eb0ff0',
    messagingSenderId: '317448814289',
    projectId: 'rental-app-2ba43',
    authDomain: 'rental-app-2ba43.firebaseapp.com',
    storageBucket: 'rental-app-2ba43.appspot.com',
    measurementId: 'G-BJ2TRTQ2EG',
  );
}
